### ISSUE TITLE
Do not enter unnecessary blank lines

### ISSUE THREAD

**Issue by norotime** [Francis27888/house_rent#3]
https://github.com/Francis27888/house_rent/blob/4a426ca07f3b5861418b04655b12a75a303e23a2/app/controllers/about_controller.rb#L3

**Comment by norotime** [comment]
https://github.com/Francis27888/house_rent/blob/master/app/controllers/contact_controller.rb#L3

I think there are other things. Please correct it.

**Comment by Francis27888** [comment]
I removed all blank lines
