### ISSUE TITLE
Use %i notation to reduce code amount

### ISSUE THREAD

**Issue by norotime** [Francis27888/house_rent#6]
https://github.com/Francis27888/house_rent/blob/4a426ca07f3b5861418b04655b12a75a303e23a2/app/controllers/application_controller.rb#L7

**Comment by norotime** [comment]
@Francis27888 Like this

before
```
 permitted_params = [:email, :password, :password_confirmation, :names,:phone_number,:user_category] 
```
after
```
 permitted_params = %[ email password password_confirmation names phone_number user_category] 
```

It's convenient, right?
I think that there are others, so please fix it.

**Comment by Francis27888** [comment]
i changed this line
` permitted_params = [:email, :password, :password_confirmation, :names,:phone_number,:user_category] `
by
`permitted_params = %[ email password password_confirmation names phone_number user_category] `
then after adding the line updating a user doesn't work anymore. what can i do to change it and functionality still the same.

**Comment by Francis27888** [comment]
I got it to add an `i`

`permitted_params = %i[ email password password_confirmation names phone_number user_category]`
